### ISSUE TITLE
Improve restock requests

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#33]
# Goal
Improve the restock request menu to:
- Search for only existing items by name
- Check if that item is already available in backstock, and if so encourage the user to ask a steward to put new material out
- Check if there is already a pending restock request for that item
- Automatically submit a request with the item name and order url (quantity is tricky, maybe we have a form element to ask the steward to input the current quantity when submitting and Kim will order an appropriate amount from that information)

# Subtasks
- [ ] Requires: #28, #24 
- [ ] Make people log requests by inputting an id
- [ ] Create a new restock request backend with information:
	- [ ] Item uuid, name, reorder url
	- [ ] Current quantity
	- [ ] Name of steward requesting
	- [ ] Timestamp
	- [ ] Status (waiting response, ordered, rejected)
	- [ ] ??
- [ ] New input for restocks, possibly as a button on each item in the inventory page
	- [ ] If logged in as user:
		- [ ] On click, show confirmation to verify that stock is low
		- [ ] After confirmation, check quantities of item in alternate locations
		- [ ] If have quantity, inform user to ask steward to restock or update quantity
		- [ ] Log responses
	- [ ] If logged in as steward:
		- [ ] Show all locations this item can be found, ask them to update quantities if not correct (LOG)
		- [ ] Confirmation button to submit official restock request, either ask for current quantity or suggested quantity to purchase
- [ ] New button for requesting new materials not yet in the space
- [ ] New kiosk system for restocks (Allow inventory users to see it too while you're making a new one anyway!)
	- [ ] Show current and past restocks
	- [ ] Button to change status (default waiting response, change to ordered, completed, or rejected)
		- [ ] On change, connect to restock request logs for users an email all people who have asked about restocking this item
		- [ ] On change to rejected or completed, mark user request logs as inactive
	- [ ] search by name (to show history)?
	- [ ] Maybe stats
