### ISSUE TITLE
Machine status overview

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#34]
# Goal
Create an overview page for the current status of machines in the space. This page would be visible to all users to show our machine uptime, but also editable by floor stewards to mark machines as broken and give an explanation for what happened prior to the machine breaking. Repair stewards can then mark machine repairs as in-progress, waiting for parts, and eventually back online.

# Subtasks
- [ ] Determine which machines deserve a status
- [ ] Backend support for changing status of machines, with authentication based on login
- [ ] Page front end
  - [prelim idea](https://www.figma.com/design/ybsdmeXzqfzWpxzmp33YTU/MAKE-Equipment-Status-Mockup?node-id=0-1&t=tuKtVR0llvu7Cg9o-0)
  - Nice green/red lights
  - Drop downs per area of the space?
- [ ] Uptime statistics
