### ISSUE TITLE
Steward log system

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#35]
# Goal
Create a user- (and mobile-) friendly interface for stewards to log activities they did on shift. This data will be invaluable for inventory, repair, cleaning, statistics, etc.

# Subtasks
- [ ] Consider the best format to input answers
	- [ ] Must be extremely easy, intuitive, and user friendly or else stewards *will* not fill it out
- [ ] Consider the options for things to log
	- [ ] Update the current quantity of an inventory item
	- [ ] Refill stock from overstock for an item with low inventory
	- [ ] Put away a new package of new inventory stock
	- [ ] Refill filament/resin/powder on a 3D printer
	- [ ] Refill ink or paper from the LFP or the Cage printer
	- [ ] Clean a machine or area of operation
	- [ ] Mark a machine for repair
	- [ ] Repaired a machine
	- [ ] Performed maintenance on a machine
	- [ ] Completed a task board task
- [ ] Implement log backends
- [ ] Implement form input
	- [ ] MUST WORK ON MOBILE
