### ISSUE TITLE
Log long-term Bambu printer status

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#36]
# Goal
Create a long-term DB cache of times when the Bambu printers change status (idle to printing to failed)
With this, also make it so the status for each printer on the printer page is only based on the most recent status update, discarding all other statuses.

# Subtasks
- [ ] Update DB schema with a new long term log
- [ ] Reroute printer update call to create a new DB item only if status of printer has changed
- [ ] Update current printer log status DB to only keep 1 (most recent) status per printer, instead of last 50 statuses total
