### ISSUE TITLE
Create a steward signup page for events

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#37]
# Goal
Create a page accessible to stewards used to sign up for upcoming events. This will allow head stewards to have an log of who has/will be able to attend events.

# Subtasks
- [ ] Create a new DB collection for internal events, which should include
  - [ ] the event name
  - [ ] a description of the event
  - [ ] date/time
  - [ ] number of stewards needed
  - [ ] list of steward proficiencies that are needed/wanted for the event
  - [ ] list of stewards signed up for event
- [ ] Implement a way to modify and add new events in the management console, which would look something akin to the workshop creation tab
- [ ] Modify the steward resources tab to include a table of upcoming events and allow people to click to signup
 - [ ] automated email reminders would also be nice
