### ISSUE TITLE
Tool/Material spotlight of the week

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#38]
# Goal
Create a popup/announcement on the main front page that highlights a tool or material of the week. This would be a continuation of the new tool/material spotlight that exists in the weekly Makerspace announcement email. The actual announcement information (body text, tool name, photo, etc.) would be created by the Outreach department.

# Subtasks
- [ ] Spotlights need the following information:
  - [ ] item uuid/name
  - [ ] title
  - [ ] body text
  - [ ] item image (optional)
  - [ ] Date range of activity (start/end date) to display on the main page
- [ ] Create a DB backend to store weekly spotlights
- [ ] Create a management backend for creating tool/material spotlights. This would likely look similar to the workshop editor tab
- [ ] Implement a front end popup for the spotlight, which should be available on the front website page
  - [ ] Make the button for the popup look nice! We want people to click it!
