### ISSUE TITLE
Update bug contact email to point to webmaster information

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#44]
# Goal
The bug contact email on the main Settings page currently tells users to report bugs to Ethan Vazquez. It'd be better if this information was queried from the webmaster name and email in the config file. 

# Subtasks
- [x] Update Settings page to point to webmaster email in config
- [x] update config file on server with new contact information
- [ ] Add webmaster name as a variable in config if not already present
