### ISSUE TITLE
Make workshop required proficiencies actually required

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#46]
# Goal
When a user attempts to sign up/RSVP/join the waitlist for a workshop, they should have already passed all the required quizzes listed for that workshop. If not, they should not be able to sign up.

# Subtasks
- [ ] Create an error popup to indicate to users that they must pass the required quizzes
 - [ ] Alternatively, this could be done by making the button disabled but have a hover tooltip indicating that quizzes aren't passed yet
- [ ] When the workshop join waitlist/RSVP button is clicked, check in the backend whether the user has passed the required quizzes for that workshop
 - [ ] if so, add them to the workshop
 - [ ] if not, show the popup/error
