### ISSUE TITLE
Update CSS styling everywhere to be more inclusive to smaller screens

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#48]
# Goal
There are a number of places in the site where elements unnecessarily overflow, which could be improved with many intricate modifications of the stylesheet. The most egregious of these places are listed in the subtasks, but giving a good once-over to a lot of the site would be worthwhile.

# Subtasks
- [ ] Update the home schedule page to not overflow
- [ ] Update styles for the rest of the home page
- [ ] Update styles in the checkout kiosk
- [ ] Update styles in the management kiosk
- [ ] Update styles anywhere else necessary
