### ISSUE TITLE
Add images to inventory items

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#51]
# Goal
When searching for items in inventory, it could be nice to show a preview image of what the actual item looks like, so users can know exactly what the item is in real life. It would be a massive undertaking to add images to every item, which would likely need to happen over a summer.

# Subtasks
- [ ] Modify the InventoryItem schema to include an image link
- [ ] Implement a way to add images to items in the inventory editor
- [ ] Implement a way for users to see the image preview in the inventory search (likely in the More Info tab)
- [ ] Update inventory items with images
