### ISSUE TITLE
Make a nicer default alert popup

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#55]
# Goal
Create a nice global alert popup for things like warnings, errors, etc.
This can easily be an implementation of an existing popup framework, it would just need some surrounding functions to edit the content/buttons present.

# Subtasks
- [ ] Find/create a nice looking popup to replace the default HTML `alert`s currently used
  - [ ] Should have a header text, body text, and variable number/content of buttons (OK, Cancel, Delete, etc.)
- [ ] Consider how to show the popup
  - [ ] Could be one element that exists on all pages that is hidden by default, and when we want a given error we just call a function to modify the header/text/buttons available
  - [ ] Alternatively, could be an element that is dynamically added/removed from the page on a function call, but that could be trickier
- [ ] Replace existing popups with the new system
  - [ ] Delete confirmations
  - [ ] Error warnings
  - [ ] etc.
