### ISSUE TITLE
Update checkout kiosk to refresh views of inventory and user information on change

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#76]
# Goal
When items are checked out or users are certified, we should update appropriate sections of the viewport to reflect the changes. Namely, this would involve resubmitting the inventory search to show an updated quantity checked out, and resubmitting the user search to show new certifications, respectively.

# Subtasks
- [ ] On checkout, call submitInventorySearch with the same input to update the view of quantity checked out
- [ ] On adding a certification, render user info again to show the updated certification
- [ ] Additionally, this could be extended to the main page to recall submitInventorySearch any time the inventory page is opened
  - [ ] This will avoid the bug where stewards who logged in, submitted a search, then logged out without doing another search keeps the steward-only view of inventory items until a new search is submitted.
