### ISSUE TITLE
Checkouts Kiosk Edits

### ISSUE THREAD

**Issue by abe-3** [HMC-Makerspace/MAKE#82]
# Goal
The reservation system is unclear. We should not allow checkouts to an item if it is reserved if there are only so many left. Additionally, the date input box for reserving items is unclear in its purpose and also doesn't work for reserving things.

# Subtasks
- [ ] Remove date input box
- [ ] Custom Reservation and Custom Checkout should trigger a pop-up where steward can put a date
- [ ] "For Break is ambiguous", remove completely and replace with custom checkout
- [ ] Reservation Button should reserve as goal suggests, not check it out for a future date
